// src/utils/contractABI.js
// Real ABI generated by: npx hardhat compile
// Matches Voting.sol exactly — do NOT manually edit.

const VotingABI = [
  // ── Events ──────────────────────────────────────────────────────────
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true,  "internalType": "uint256", "name": "candidateId", "type": "uint256" },
      { "indexed": false, "internalType": "string",  "name": "name",        "type": "string"  },
      { "indexed": false, "internalType": "string",  "name": "party",       "type": "string"  }
    ],
    "name": "CandidateAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": false, "internalType": "bool",   "name": "isActive",     "type": "bool"   },
      { "indexed": false, "internalType": "string", "name": "electionName", "type": "string" }
    ],
    "name": "ElectionStatusChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true,  "internalType": "uint256", "name": "candidateId", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "timestamp",   "type": "uint256" }
    ],
    "name": "VoteCast",
    "type": "event"
  },
  // ── Constructor ────────────────────────────────────────────────────
  { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
  // ── Write Functions ────────────────────────────────────────────────
  {
    "inputs": [
      { "internalType": "string", "name": "_name",  "type": "string" },
      { "internalType": "string", "name": "_party", "type": "string" }
    ],
    "name": "addCandidate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "string", "name": "_electionName", "type": "string" }],
    "name": "createElection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "endVoting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "startVoting",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "_candidateId", "type": "uint256" }],
    "name": "vote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  // ── View / Pure Functions ──────────────────────────────────────────
  {
    "inputs": [],
    "name": "admin",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "name": "candidates",
    "outputs": [
      { "internalType": "uint256", "name": "id",        "type": "uint256" },
      { "internalType": "string",  "name": "name",      "type": "string"  },
      { "internalType": "string",  "name": "party",     "type": "string"  },
      { "internalType": "uint256", "name": "voteCount", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "candidateCount",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "address", "name": "_voter", "type": "address" }],
    "name": "checkIfVoted",
    "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "electionCreated",
    "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "electionName",
    "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllCandidates",
    "outputs": [
      {
        "components": [
          { "internalType": "uint256", "name": "id",        "type": "uint256" },
          { "internalType": "string",  "name": "name",      "type": "string"  },
          { "internalType": "string",  "name": "party",     "type": "string"  },
          { "internalType": "uint256", "name": "voteCount", "type": "uint256" }
        ],
        "internalType": "struct Voting.Candidate[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getElectionInfo",
    "outputs": [
      { "internalType": "string",  "name": "name",          "type": "string"  },
      { "internalType": "bool",    "name": "isActive",      "type": "bool"    },
      { "internalType": "uint256", "name": "numCandidates", "type": "uint256" },
      { "internalType": "uint256", "name": "votes",         "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "name": "hasVoted",
    "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalVotes",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "votingActive",
    "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
    "stateMutability": "view",
    "type": "function"
  }
];

export default VotingABI;
